module.exports = [
  { name: "Fiction" },
  { name: "Science Fiction" },
  { name: "Historical Fiction" },
  { name: "Horror" },
  { name: "Fantasy" },
  { name: "Science" },
  { name: "Adventure" },
  { name: "Thriller" },
  { name: "Self-Help" },
  { name: "Drama" },
  { name: "Legal thriller" },
  { name: "Dystopian" },
  { name: "Action" },
  { name: "Romance" },
  { name: "Political Thriller" },
  { name: "Spanish Literature" },
  { name: "Historical Drama" },
  { name: "Short Stories" },
  { name: "Latin American Literature" },
  { name: "Mystery" },
  { name: "Non-Fiction" },
  { name: "Business" },
  { name: "Classic Literature" },
  { name: "Magic" },
  { name: "Inspirational" },
  { name: "Classics" },
  { name: "Post-Apocalyptic" },
  { name: "Psychological" },
];
